# Forced Signet in Docker
server=1
txindex=0
prune=1000

# RPC
rpcuser= <rpcuser>
rpcpassword= <rpcpassword>
# Bind to all interfaces for external access
rpcbind=0.0.0.0
# Allow access from all interfaces
rpcallowip=0.0.0.0/0

# ZMQ for LND (required for real-time notifications)
# Broadcasts the full content of new blocks
zmqpubrawblock=tcp://0.0.0.0:28332
# Broadcasts the full content of new transactions
zmqpubrawtx=tcp://0.0.0.0:28333

# Performance optimization and resource management
dbcache=2500
# Restrict to 1 thread for CPU stability
par=1
maxmempool=50
