[Bitcoin]
bitcoin.active=1
bitcoin.signet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=bitcoind:38332
bitcoind.rpcuser=<rpcuser>
bitcoind.rpcpass=<rpcpassword>
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333

[Application Options]
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
listen=0.0.0.0:9735
tlsextraip=127.0.0.1
tlsextraip=<public_ip>
wallet-unlock-password-file=/path/.lnd/password.txt